import type { ThemeId } from "./types";

export type ThemeLabels = {
  totalScoreboard: [string, string]; // two lines
  currentScoreboard: [string, string];
  headerTitle: string;               // shown before the level digit, e.g. "VOLTORB Flip Lv."
  headerSubtitle: string;            // second row of the header banner
  voltorbMessage: string;            // right-of-voltorb-icon tagline
  legendMultipliers: string;         // right-of-1/2/3-boxes, e.g. "...x1! ...x2! ...x3!"
};

export type ThemeDef = {
  id: ThemeId;
  name: string;
  description: string;
  cost: number;
  bgUrl: string;
  bgmUrl: string;
  overlay?: string;
  tilePalette?: {
    blank?: string;
  };
  labels: ThemeLabels;
};

const ASSETS = "/games/super-voltorb-flip";

export const THEMES: Record<ThemeId, ThemeDef> = {
  classic: {
    id: "classic",
    name: "Game Corner Classic",
    description: "The faithful HGSS recreation. Green DS background, pixel tiles.",
    cost: 0,
    bgUrl: `linear-gradient(180deg, #5ab859 0%, #3f8a3f 100%)`,
    bgmUrl: `${ASSETS}/music/theme-classic.mp3`,
    labels: {
      totalScoreboard: ["Total", "Collected Coins"],
      currentScoreboard: ["Coins Collected in", "Current Game"],
      headerTitle: "VOLTORB Flip Lv.",
      headerSubtitle: "Flip the Cards and Collect Coins!",
      voltorbMessage: "Game Over! 0!",
      legendMultipliers: "...x1! ...x2! ...x3!",
    },
  },
  meadow: {
    id: "meadow",
    name: "Starter's Meadow",
    description: "Soft green meadow with wooden tile frames. A warm early-game vibe.",
    cost: 2500,
    bgUrl: `linear-gradient(180deg, #c8e88a 0%, #8fbf5a 100%)`,
    bgmUrl: `${ASSETS}/music/theme-meadow.mp3`,
    overlay: "meadow-grass-pattern",
    labels: {
      totalScoreboard: ["Meadow", "Fortune"],
      currentScoreboard: ["This", "Meadow Run"],
      headerTitle: "MEADOW Flip Lv.",
      headerSubtitle: "Through the tall grass we go!",
      voltorbMessage: "Pollen blast! 0!",
      legendMultipliers: "leaf1 bud2 bloom3",
    },
  },
  twilight: {
    id: "twilight",
    name: "Twilight Route",
    description: "Orange-pink sunset, silhouetted trees in the distance.",
    cost: 5000,
    bgUrl: `linear-gradient(180deg, #ff9966 0%, #ff5e8a 60%, #6a2c70 100%)`,
    bgmUrl: `${ASSETS}/music/theme-twilight.mp3`,
    overlay: "twilight-silhouette",
    labels: {
      totalScoreboard: ["Twilight", "Hoard"],
      currentScoreboard: ["Evening's", "Haul"],
      headerTitle: "TWILIGHT Flip Lv.",
      headerSubtitle: "Beat the dusk before night!",
      voltorbMessage: "Dusk bomb! 0!",
      legendMultipliers: "dawn1 dusk2 nite3",
    },
  },
  thunder: {
    id: "thunder",
    name: "Thunder Hall",
    description: "Electric gym vibes — yellow-and-black with crackling palette.",
    cost: 10000,
    bgUrl: `linear-gradient(180deg, #fde047 0%, #facc15 35%, #1a1a1a 100%)`,
    bgmUrl: `${ASSETS}/music/theme-classic.mp3`,
    labels: {
      totalScoreboard: ["Stored", "Watts"],
      currentScoreboard: ["This Round's", "Charge"],
      headerTitle: "VOLT Flip Lv.",
      headerSubtitle: "Shock the boxes for current!",
      voltorbMessage: "Short circuit! 0!",
      legendMultipliers: "spark1 bolt2 storm3",
    },
  },
  rainbow: {
    id: "rainbow",
    name: "Rainbow Feather",
    description: "Legendary tier — gold and rainbow gradient for champions.",
    cost: 30000,
    bgUrl: `linear-gradient(135deg, #ef4444 0%, #f59e0b 20%, #eab308 40%, #22c55e 60%, #3b82f6 80%, #a855f7 100%)`,
    bgmUrl: `${ASSETS}/music/theme-classic.mp3`,
    labels: {
      totalScoreboard: ["Legendary", "Hoard"],
      currentScoreboard: ["Current", "Plume"],
      headerTitle: "RAINBOW Flip Lv.",
      headerSubtitle: "Earn your champion crest!",
      voltorbMessage: "Ember feather! 0!",
      legendMultipliers: "fethr1 plume2 crest3",
    },
  },
};

/**
 * Resolve a per-theme sprite path. Non-classic themes have their own
 * tinted variants generated by scripts/tint-chrome-per-theme.py — the
 * tinted PNG sits in a {themeId}/ subdir alongside the original (e.g.
 * `button/memo/twilight/open.png`). Classic uses the base path so we
 * don't ship duplicate green sprites.
 */
export function themedAsset(themeId: ThemeId, path: string): string {
  const base = "/games/super-voltorb-flip/sprites";
  if (themeId === "classic") return `${base}/${path}`;
  const lastSlash = path.lastIndexOf("/");
  const folder = path.slice(0, lastSlash);
  const file = path.slice(lastSlash + 1);
  return `${base}/${folder}/${themeId}/${file}`;
}

export const DEFAULT_THEME: ThemeId = "classic";
export const THEME_ORDER: ThemeId[] = [
  "classic",
  "meadow",
  "twilight",
  "thunder",
  "rainbow",
];
